Repository firstbatchxyz/dkn-compute-node, pull requests merged in 2024-11, with the labels that each got.

#139 added error reporting on publish, update workflows
  Cargo.lock
  Cargo.toml
  compute/src/config.rs
  compute/src/handlers/workflow.rs
  compute/src/node.rs
  compute/src/utils/available_nodes.rs
  p2p/src/behaviour.rs
  p2p/src/client.rs
  workflows/src/apis/serper.rs
  workflows/src/providers/gemini.rs
  workflows/src/providers/ollama.rs
  workflows/src/providers/openai.rs
Labels: bug

#141 feat: set conn limit
  Cargo.lock
  Cargo.toml
  compute/src/node.rs
  p2p/src/behaviour.rs
Labels: enhancement

#146 feat: added openrouter support
  .env.example
  Cargo.lock
  Cargo.toml
  Dockerfile
  compute/src/utils/message.rs
  p2p/src/client.rs
  p2p/src/lib.rs
  workflows/src/config.rs
  workflows/src/providers/mod.rs
  workflows/src/providers/openrouter.rs
Labels: enhancement

#142 TPS reporter
  Cargo.lock
  workflows/Cargo.toml
  workflows/src/bin/tps.rs
  workflows/src/lib.rs
Labels: enhancement

#150 feat: p2p in a separate thread
  Cargo.lock
  compute/src/handlers/pingpong.rs
  compute/src/handlers/workflow.rs
  compute/src/main.rs
  compute/src/node.rs
  compute/src/utils/available_nodes/mod.rs
  p2p/Cargo.toml
  p2p/README.md
  p2p/src/client.rs
  p2p/src/commands.rs
  p2p/src/lib.rs
  p2p/tests/listen_test.rs
Labels: enhancement

#148 feat: multi-network & peer disconnections
  Cargo.lock
  Cargo.toml
  compute/src/config.rs
  compute/src/handlers/pingpong.rs
  compute/src/handlers/workflow.rs
  compute/src/lib.rs
  compute/src/main.rs
  compute/src/node.rs
  compute/src/utils/available_nodes.rs
  compute/src/utils/available_nodes/mod.rs
  compute/src/utils/available_nodes/statics.rs
  compute/src/utils/message.rs
  p2p/Cargo.toml
  p2p/README.md
  p2p/src/behaviour.rs
  p2p/src/client.rs
  p2p/src/commands.rs
  p2p/src/lib.rs
  p2p/src/protocol.rs
  p2p/tests/listen_test.rs
  workflows/src/apis/jina.rs
  workflows/src/bin/tps.rs
  workflows/src/providers/gemini.rs
  workflows/src/providers/openai.rs
  workflows/src/providers/openrouter.rs
  workflows/tests/models_test.rs
Labels: bug, enhancement
